name: Build My Application

on: push

jobs:
    build:
      name: Build our App
      runs-on: ubuntu-latest
      steps:
        - name: Pull repo
        - uses: actions/checkout@v2
        # - name: Hello world
        #   uses: actions/hello-world-javascript-action@v1
        #   with:
        #     who-to-greet: 'Mona the Octocat'
        #   id: hello
        - name: Print Current Directory
          run: pwd
        - name: List Files in Directory
          run: ls
        - name: Check Dotnet CLI
          run: dotnet
        - name: Check NPM Cli
          run: npm